// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 3.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'premium_todo';

  static const String assets_icon_png = 'assets/icon.png';
  static const String premium_todo$assets_icon_png = 'packages/premium_todo/assets/icon.png';

  static const String assets_logo_svg = 'assets/logo.svg';
  static const String premium_todo$assets_logo_svg = 'packages/premium_todo/assets/logo.svg';

  static const String assets_upload_png = 'assets/upload.png';
  static const String premium_todo$assets_upload_png = 'packages/premium_todo/assets/upload.png';
}
