// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdQFv14b8f9grGu2z-6T2J6ibiBpZ1HY',
    appId: '1:677476755190:web:11ade89e85183414c42ed7',
    messagingSenderId: '677476755190',
    projectId: 'pds-tp',
    authDomain: 'pds-tp.firebaseapp.com',
    storageBucket: 'pds-tp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOV8pjP7nYlU8bgQhQsKzCOXnx1qqoDA',
    appId: '1:677476755190:android:2e55f3f72a5b6600c42ed7',
    messagingSenderId: '677476755190',
    projectId: 'pds-tp',
    storageBucket: 'pds-tp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlWuAEk4d7SmHckdhTjmBcQDG_CorptE',
    appId: '1:677476755190:ios:741e451245f44538c42ed7',
    messagingSenderId: '677476755190',
    projectId: 'pds-tp',
    storageBucket: 'pds-tp.appspot.com',
    iosClientId: '677476755190-djvas1had6ua0u9iagg2q4g1lqkus952.apps.googleusercontent.com',
    iosBundleId: 'com.squad.premium.todo',
  );
}
