name: premium_todo
description: ToDo list
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  assets_gen: ^1.5.0
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  get_it: ^7.2.0
  google_fonts: ^4.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
